"""Message content utilities for TauErgon.

Pure utility functions for message sanitization, synthetic message handling,
and text extraction. Zero dependencies on other agent modules.

Extracted from agent_context.py to break circular dependencies and improve
module organization.
"""

from __future__ import annotations

# ── User message prefix protocol ────────────────────────────────────────────────
# All user messages are prefixed with [U:TYPE | N:stack] to indicate their type
# and nesting level. Real user messages have [U:real | N:...], synthetic messages
# have other types ([U:meta | N:...], [U:confirm | N:...], etc.).
# Format: [U:TYPE | N:stack] Content
# Types: real, meta, confirm, inject, system, fork, subagent, redirect
_USER_PREFIX_PATTERN = "[U:"
_REAL_USER_PREFIX = "[U:real | N:"

# Legacy synthetic prefix (backward compatibility)
_SYNTHETIC_PREFIX = "[SYSTEM-SYNTHETIC: "


def is_synthetic_message(msg: dict) -> bool:
    """Check if any message (user or assistant) is synthetic.

    A message is synthetic if it has a user message prefix with a synthetic type
    (meta, confirm, inject, system). Real user messages (real, fork, subagent,
    redirect) are NOT synthetic, even though they have prefixes.

    Also checks for legacy [SYSTEM-SYNTHETIC: prefix for backward compatibility.

    Args:
        msg: A message dictionary to check.

    Returns:
        True if the message was system-injected, False otherwise.
    """
    # Synthetic types: meta, confirm, inject, system
    # Non-synthetic types: real, fork, subagent, redirect
    _SYNTHETIC_TYPES = {"meta", "confirm", "inject", "system"}

    content = msg.get("content", "")
    if isinstance(content, str):
        # Check for new prefix format
        if content.startswith(_USER_PREFIX_PATTERN):
            user_type = _get_user_type_from_content(content)
            return user_type in _SYNTHETIC_TYPES
        # Legacy check (backward compatibility)
        return content.startswith("[SYSTEM-SYNTHETIC: ")
    if isinstance(content, list):
        for part in content:
            if isinstance(part, dict) and part.get("type") == "text":
                text = part.get("text", "")
                # Check for new prefix format
                if text.startswith(_USER_PREFIX_PATTERN):
                    user_type = _get_user_type_from_content(text)
                    return user_type in _SYNTHETIC_TYPES
                # Legacy check (backward compatibility)
                if text.startswith("[SYSTEM-SYNTHETIC: "):
                    return True
    return False


def _get_user_type_from_content(content: str) -> str | None:
    """Extract user type from prefixed content."""
    if not isinstance(content, str) or not content.startswith(_USER_PREFIX_PATTERN):
        return None
    try:
        end = content.index("]")
        prefix = content[1:end]  # "U:TYPE | N:stack"
        type_part = prefix.split(" | ")[0]  # "U:TYPE"
        return type_part[2:]  # "TYPE"
    except (ValueError, IndexError):
        return None


def _extract_text_content(msg: dict) -> str:
    """Extract text content from a message, handling multimodal content."""
    content = msg.get("content", "")
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts = [c.get("text", "") for c in content if c.get("type") == "text"]
        return " ".join(parts)
    return ""


def get_last_real_user_prompt(context_messages: list[dict]) -> str:
    """Find the last genuine user message in context (excluding synthetic messages).

    Scans the context backwards for the last user message that was NOT
    auto-generated by loop escalation or recovery. Returns the full content
    without truncation.

    Args:
        context_messages: List of context messages to search.

    Returns:
        str: The last real user prompt, or a fallback message if not found.
    """
    for msg in reversed(context_messages):
        if msg.get("role") == "user" and not is_synthetic_message(msg):
            return _extract_text_content(msg)
    return "(no real user prompt found)"


# ── Sanitization ──────────────────────────────────────────────────────────────

_SURROGATE_DELETE = str.maketrans("", "", "".join(chr(c) for c in range(0xD800, 0xE000)))


def _sanitize_text(text: str) -> str:
    """Strip lone UTF-16 surrogates from text.

    Surrogates (U+D800–U+DFFF) are never valid in UTF-8/UTF-32.
    They only appear as pairs in UTF-16 encoding.
    Lone surrogates cause tokenizer rejection (TextEncodeInput error).
    """
    return text.translate(_SURROGATE_DELETE)


def _sanitize_content(content: str | list) -> str | list:
    """Sanitize content — handles plain string, multimodal list, and nested dicts."""
    if isinstance(content, str):
        return _sanitize_text(content)
    if isinstance(content, list):
        return [
            _sanitize_text(item) if isinstance(item, str)
            else {**item, "text": _sanitize_text(item["text"])}
            if isinstance(item, dict) and item.get("type") == "text" and item.get("text")
            else item
            for item in content
        ]
    return content


__all__ = [
    "_SYNTHETIC_PREFIX",
    "_sanitize_content",
    "_sanitize_text",
    "get_last_real_user_prompt",
    "is_synthetic_message",
]
