"""Message content utilities for TauErgon.

Pure utility functions for message sanitization, synthetic message handling,
and text extraction. Zero dependencies on other agent modules.

Extracted from agent_context.py to break circular dependencies and improve
module organization.
"""

from __future__ import annotations

# ── Synthetic message protocol ────────────────────────────────────────────────
# All system-injected messages use this prefix so they can be reliably detected
# and excluded from user-boundary calculations (undo, get_last_real_user_prompt).
# Format: [SYSTEM-SYNTHETIC: <category>] <content>
# Categories: end_turn_reminder, escalation, reflection, turn_started,
#             turn_closed, command, recovery
_SYNTHETIC_PREFIX = "[SYSTEM-SYNTHETIC: "


def is_synthetic_message(msg: dict) -> bool:
    """Check if any message (user or assistant) is synthetic.

    Args:
        msg: A message dictionary to check.

    Returns:
        True if the message was system-injected, False otherwise.
    """
    content = msg.get("content", "")
    if isinstance(content, str):
        return content.startswith(_SYNTHETIC_PREFIX)
    if isinstance(content, list):
        for part in content:
            if isinstance(part, dict) and part.get("type") == "text":
                if part.get("text", "").startswith(_SYNTHETIC_PREFIX):
                    return True
    return False


def make_synthetic_user(category: str, content: str) -> dict:
    """Create a synthetic user message with the standard marker.

    Args:
        category: The synthetic message category (e.g., 'end_turn_reminder').
        content: The message content (without prefix).

    Returns:
        A message dict ready to append to context.
    """
    return {
        "role": "user",
        "content": f"{_SYNTHETIC_PREFIX}{category}] {content}",
    }


def _extract_text_content(msg: dict) -> str:
    """Extract text content from a message, handling multimodal content."""
    content = msg.get("content", "")
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts = [c.get("text", "") for c in content if c.get("type") == "text"]
        return " ".join(parts)
    return ""


def get_last_real_user_prompt(context_messages: list[dict]) -> str:
    """Find the last genuine user message in context (excluding synthetic messages).

    Scans the context backwards for the last user message that was NOT
    auto-generated by loop escalation or recovery. Returns the full content
    without truncation.

    Args:
        context_messages: List of context messages to search.

    Returns:
        str: The last real user prompt, or a fallback message if not found.
    """
    for msg in reversed(context_messages):
        if msg.get("role") == "user" and not is_synthetic_message(msg):
            return _extract_text_content(msg)
    return "(no real user prompt found)"


# ── Sanitization ──────────────────────────────────────────────────────────────

_SURROGATE_DELETE = str.maketrans("", "", "".join(chr(c) for c in range(0xD800, 0xE000)))


def _sanitize_text(text: str) -> str:
    """Strip lone UTF-16 surrogates from text.

    Surrogates (U+D800–U+DFFF) are never valid in UTF-8/UTF-32.
    They only appear as pairs in UTF-16 encoding.
    Lone surrogates cause tokenizer rejection (TextEncodeInput error).
    """
    return text.translate(_SURROGATE_DELETE)


def _sanitize_content(content: str | list) -> str | list:
    """Sanitize content — handles plain string, multimodal list, and nested dicts."""
    if isinstance(content, str):
        return _sanitize_text(content)
    if isinstance(content, list):
        return [
            _sanitize_text(item) if isinstance(item, str)
            else {**item, "text": _sanitize_text(item["text"])}
            if isinstance(item, dict) and item.get("type") == "text" and item.get("text")
            else item
            for item in content
        ]
    return content


__all__ = [
    "_SYNTHETIC_PREFIX",
    "_sanitize_content",
    "_sanitize_text",
    "get_last_real_user_prompt",
    "is_synthetic_message",
    "make_synthetic_user",
]
